### ISSUE TITLE
Validate path for classroom training materials within VM

### ISSUE THREAD

**Issue by ian-flores** [rstudio/team-admin.rstudio.com#46]
We need to standardize the path of the classroom training materials within the VM. This would entail modifying our deployment infrastructure. This is not a change in this repo but it is highly related and should be documented with it.

**Comment by ian-flores** [comment]
[HERE](https://team-admin.rstudio.com/rstudio-server-pro/lab-security/#task-create-sssdconf-file) we say : `/usr/share/class/class-repo/`

**Comment by ian-flores** [comment]
[HERE](https://team-admin.rstudio.com/getting-started/lab-ssh-in/#task-explore-some-folder-locations) we say : `/usr/share/class`

**Comment by ian-flores** [comment]
In the [class admin app](https://github.com/rstudio/training-tool-admin/edit/team_admin_training_dev/class_admin/R/mod_class_mgmt.R) we say it's: `/usr/share/class/pro_admin_training_assets`

**Comment by ian-flores** [comment]
I'm going to standardize all conventions to be `/usr/share/class` as it is the most concise.

**Comment by andrie** [comment]
Fixed in #49
